name: Development

on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call: 

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node/express-prisma-typescript
    timeout-minutes: 10
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18

      - name: "install npm@latest"
        run: npm i -g npm@10.8.2

      - name: "Install dependencies"
        run: npm install
        
      - name: "Run tests"
        run: npm run test --if-present
